### ISSUE TITLE
On page refresh style reverts back to dark mode

### ISSUE THREAD

**Issue by dlublin** [Vidvox/oscqueryhtml#60]
This happens even if the page automatically refreshes due to changes in the address space.

Steps to reproduce:
1. Launch VV osc test server and load any json
2. Open webpage for control
3. Set webpage to light mode
4. Click 'Sent Path Changed' button in osc test server interface
5. Observe that webpage has been reset to dark mode on refresh

**Comment by dustmop** [comment]
So this is tricky, because there's nothing stored server side that maintains the state of the page style. The only thing we can do is set a cookie in the browser, and then, on page reload, check the cookie to see if light mode should be used, and change the style. This will have the unfortunate effect of making the page "pop" from dark mode to light mode on refresh. However, it's the only way to avoid requiring the server to server dynamic html.

**Comment by dustmop** [comment]
Implemented by c59d9d1, the user's cookie now stores the style preference.
